#
# CSE183 Assignment 7
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 7
  version: 0.1.0
  title: CSE183 Assignment 7

servers:
  - url: http://localhost:3010

paths:
  /v0/mail:
    get:
      description: Returns all EMail
      responses:
        200:
          description: Email Response
